[package]
name = "taitan-orm"
edition = "2021"
version.workspace = true
rust-version.workspace = true
license = "MIT OR Apache-2.0"
description = "Next Generation ORM based on sqlx"
homepage = "https://github.com/thegenius/taitan-orm"

[dependencies]
#taitan-orm-trait = { path = "../taitan-orm-trait" }
#taitan-orm-macro = { path = "../taitan-orm-macro", features = ["sqlite", "mysql", "postgres"] }
taitan-orm-trait = { version = "0.1.10" }
taitan-orm-macro = { version = "0.1.10", features = ["sqlite", "mysql", "postgres"] }

sqlx = { workspace = true }
serde = { workspace = true }

time = { workspace = true }
uuid = { workspace = true }
bigdecimal = { workspace = true }

tracing = { workspace = true }
path-absolutize = { workspace = true }
askama = { workspace = true }


[dev-dependencies]
tracing-subscriber = { workspace = true }






