[package]
name = "taitan-orm"
edition = "2021"
version.workspace = true
rust-version.workspace = true
license = "MIT OR Apache-2.0"
description = "Next Generation ORM based on sqlx"
homepage = "https://github.com/thegenius/taitan-orm"

[dependencies]
taitan-orm-trait = { path = "../taitan-orm-trait" }
taitan-orm-macro = { path = "../taitan-orm-macro" }
#taitan-orm-trait = { version = "0.1.9" }
#taitan-orm-macro = { version = "0.1.9" }
sqlx = {workspace = true}
serde = {workspace = true}
time = {workspace = true}
uuid = {workspace = true}
tracing = {workspace = true}
thiserror = {workspace = true}
path-absolutize = {workspace = true}
rinja = "0.3.5"

#bit-vec = "0.8.0"

[dev-dependencies]
anyhow = "1.0.94"
testcontainers = "0.23.1"
testcontainers-modules = { version = "0.11.4", features = ["mysql"] }
tracing-test = {workspace = true}
tracing-subscriber = {workspace = true}






