name: CI

on:
  push: { branches: [main] }
  pull_request:
  schedule: [cron: "40 1 * * *"]

jobs:
  install:
    name: Rust ${{matrix.rust || '(default)'}} (toolchain-file=${{matrix.write-toolchain-file}}) (${{matrix.os}})
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        write-toolchain-file:
          - false
          - true
        rust:
          # use stable toolchain as default
          - null
          - "1.83"
          - "nightly"
          - "beta"
          - "stable"
    steps:
      - uses: actions/checkout@v4

      - shell: bash
        run: rustc --version && cargo --version

      # test the project
      - run: cargo test


